name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        pip3 install miniwdl
        make test
    - name: inspect
      run: |
        docker run -v $(pwd):/mnt vcf_line_splitter cp /usr/local/bin/vcf_line_splitter /mnt
        ldd vcf_line_splitter
        sha256sum vcf_line_splitter
    - name: upload exe
      uses: actions/upload-artifact@v2
      with:
        name: vcf_line_splitter
        path: vcf_line_splitter
    - name: docker login ghcr.io
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: push image
      run: |
        REPO="ghcr.io/mlin/vcf_line_splitter"
        TAG="$(git describe --tags --always --dirty)"
        docker tag vcf_line_splitter:latest "${REPO}:${TAG}"
        docker push "${REPO}:${TAG}"
